# Generated by Django 5.1.15 on 2026-07-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="unlocked_units",
            field=models.ManyToManyField(
                blank=True, related_name="unlocked_for", to="learn.unit"
            ),
        ),
    ]
